/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'pacastaneda' at '21/04/16 13:45' with Gradle 2.12
 *
 * @author pacastaneda, @date 21/04/16 13:45
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
